### PR TITLE
Add option to only multiply rottenflesh for zombies to prevent duplication bugs with picked up items

### PR DESCRIPTION
**Pull request by dwaynehulsman**
- Add option to only multiply rotten flesh for zombies to prevent duplication bugs with picked up items.
- Small code cleanup
- Git ignore for Intelij IDE

### CODE REVIEW

**Review by ploppyperson — CHANGES_REQUESTED** [review]
Isn't ignore-armor the same as the zombie-only-multiply-rottenflash?

**Comment by dwaynehulsman** [comment]
Rottenflesh isn't armor.

**Comment by ploppyperson** [comment]
Oh yeah sorry, but you could just set the drop chance of rotten flesh to 0.0 to achieve the same effect?

**Comment by dwaynehulsman** [comment]
The moral of the story is that any picked up item is dupable by the mob if picked up. Because it actually drops the expected amount of held items when stacked rather then just the 1.

**Review by ploppyperson — APPROVED** [review]

**Pull request merged**
